name: Push Docker Image to ECR
on:
    push:
        branches:
            - '**'
        branches-ignore:
            - master

jobs:
    build:
        name: Build & Push to AWS ECR
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: scraper-worker
                  IMAGE_TAG: ${{ github.sha }}
                  NPM_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  docker build --build-arg NPM_REG_CRED=${NPM_TOKEN} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            - name: Logout of Amazon ECR
              if: always()
              run: docker logout ${{ steps.login-ecr.outputs.registry }}
